#- Github defaults -#
lsi: false
# safe: true
# source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
##
#- Project configuration -#
##
repository: trentesimobea/trentesimobea.github.io
url: https://trentesimobea.github.io
theme: jekyll-theme-merlot
plugins: 
  # - mandatory for Github pages - #
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  # - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  # - custom supported - #
  - jekyll-seo-tag
  # - unsupported - #
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

# -seo configuration- # 
title: Trentesimo Bea
description: Festeggiamola come avremmo voluto
image: 
  path: /img/bea.jpeg
lang: it_IT
google_analytics: UA-164594656-1

# -paginate configuration- # 
# paginate: off
# paginate_path: "/blog/page:num/"
# -pagination-v2 configuration- #
pagination:
  enabled: true
  # collection: 'videos'
  # per_page: 5
  # sort_field: 'title' # default: date
  # sort_reverse: false # default: true
  # category: 'videos'
  # permalink: 'auguri/page:num/'
  # indexpage: 'auguri/index'
#-features flags-#
show_blog: true
show_excerpts: false
date_format: "%b %-d, %Y"